module.exports = {
    pageNumbers: [
    '<span epub:type="pagebreak" id="pagev" title="v"/>',
    '<span epub:type="pagebreak" id="pagevii" title="vii"/>',
    '<span epub:type="pagebreak" id="pageviii" title="viii"/>',
    '<span epub:type="pagebreak" id="pageix" title="ix"/>',
    '<span epub:type="pagebreak" id="pagex" title="x"/>',
    '<span epub:type="pagebreak" id="pagexi" title="xi"/>',
    '<span epub:type="pagebreak" id="pagexii" title="xii"/>',
    '<span epub:type="pagebreak" id="page1" title="1"/>',
    '<span epub:type="pagebreak" id="page2" title="2"/>',
    '<span epub:type="pagebreak" id="page3" title="3"/>',
    '<span epub:type="pagebreak" id="page4" title="4"/>',
    '<span epub:type="pagebreak" id="page5" title="5"/>',
    '<span epub:type="pagebreak" id="page6" title="6"/>',
    '<span epub:type="pagebreak" id="page7" title="7"/>',
    '<span epub:type="pagebreak" id="page8" title="8"/>',
    '<span epub:type="pagebreak" id="page9" title="9"/>',
    '<span epub:type="pagebreak" id="page10" title="10"/>',
    '<span epub:type="pagebreak" id="page11" title="11"/>',
    '<span epub:type="pagebreak" id="page12" title="12"/>',
    '<span epub:type="pagebreak" id="page13" title="13"/>',
    '<span epub:type="pagebreak" id="page14" title="14"/>',
    '<span epub:type="pagebreak" id="page15" title="15"/>',
    '<span epub:type="pagebreak" id="page16" title="16"/>',
    '<span epub:type="pagebreak" id="page17" title="17"/>',
    '<span epub:type="pagebreak" id="page18" title="18"/>',
    '<span epub:type="pagebreak" id="page19" title="19"/>',
    '<span epub:type="pagebreak" id="page20" title="20"/>',
    '<span epub:type="pagebreak" id="page21" title="21"/>',
    '<span epub:type="pagebreak" id="page22" title="22"/>',
    '<span epub:type="pagebreak" id="page23" title="23"/>',
    '<span epub:type="pagebreak" id="page24" title="24"/>',
    '<span epub:type="pagebreak" id="page25" title="25"/>',
    '<span epub:type="pagebreak" id="page26" title="26"/>',
    '<span epub:type="pagebreak" id="page27" title="27"/>',
    '<span epub:type="pagebreak" id="page28" title="28"/>',
    '<span epub:type="pagebreak" id="page29" title="29"/>',
    '<span epub:type="pagebreak" id="page30" title="30"/>',
    '<span epub:type="pagebreak" id="page31" title="31"/>',
    '<span epub:type="pagebreak" id="page32" title="32"/>',
    '<span epub:type="pagebreak" id="page33" title="33"/>',
    '<span epub:type="pagebreak" id="page34" title="34"/>',
    '<span epub:type="pagebreak" id="page35" title="35"/>',
    '<span epub:type="pagebreak" id="page36" title="36"/>',
    '<span epub:type="pagebreak" id="page37" title="37"/>',
    '<span epub:type="pagebreak" id="page38" title="38"/>',
    '<span epub:type="pagebreak" id="page39" title="39"/>',
    '<span epub:type="pagebreak" id="page40" title="40"/>',
    '<span epub:type="pagebreak" id="page41" title="41"/>',
    '<span epub:type="pagebreak" id="page42" title="42"/>',
    '<span epub:type="pagebreak" id="page43" title="43"/>',
    '<span epub:type="pagebreak" id="page44" title="44"/>',
    '<span epub:type="pagebreak" id="page45" title="45"/>',
    '<span epub:type="pagebreak" id="page46" title="46"/>',
    '<span epub:type="pagebreak" id="page47" title="47"/>',
    '<span epub:type="pagebreak" id="page48" title="48"/>',
    '<span epub:type="pagebreak" id="page49" title="49"/>',
    '<span epub:type="pagebreak" id="page50" title="50"/>',
    '<span epub:type="pagebreak" id="page51" title="51"/>',
    '<span epub:type="pagebreak" id="page52" title="52"/>',
    '<span epub:type="pagebreak" id="page53" title="53"/>',
    '<span epub:type="pagebreak" id="page54" title="54"/>',
    '<span epub:type="pagebreak" id="page55" title="55"/>',
    '<span epub:type="pagebreak" id="page56" title="56"/>',
    '<span epub:type="pagebreak" id="page57" title="57"/>',
    '<span epub:type="pagebreak" id="page58" title="58"/>',
    '<span epub:type="pagebreak" id="page59" title="59"/>',
    '<span epub:type="pagebreak" id="page60" title="60"/>',
    '<span epub:type="pagebreak" id="page61" title="61"/>',
    '<span epub:type="pagebreak" id="page62" title="62"/>',
    '<span epub:type="pagebreak" id="page63" title="63"/>',
    '<span epub:type="pagebreak" id="page64" title="64"/>',
    '<span epub:type="pagebreak" id="page65" title="65"/>',
    '<span epub:type="pagebreak" id="page66" title="66"/>',
    '<span epub:type="pagebreak" id="page67" title="67"/>',
    '<span epub:type="pagebreak" id="page68" title="68"/>',
    '<span epub:type="pagebreak" id="page69" title="69"/>',
    '<span epub:type="pagebreak" id="page70" title="70"/>',
    '<span epub:type="pagebreak" id="page71" title="71"/>',
    '<span epub:type="pagebreak" id="page72" title="72"/>',
    '<span epub:type="pagebreak" id="page73" title="73"/>',
    '<span epub:type="pagebreak" id="page74" title="74"/>',
    '<span epub:type="pagebreak" id="page75" title="75"/>',
    '<span epub:type="pagebreak" id="page76" title="76"/>',
    '<span epub:type="pagebreak" id="page77" title="77"/>',
    '<span epub:type="pagebreak" id="page78" title="78"/>',
    '<span epub:type="pagebreak" id="page79" title="79"/>',
    '<span epub:type="pagebreak" id="page80" title="80"/>',
    '<span epub:type="pagebreak" id="page81" title="81"/>',
    '<span epub:type="pagebreak" id="page82" title="82"/>',
    '<span epub:type="pagebreak" id="page83" title="83"/>',
    '<span epub:type="pagebreak" id="page84" title="84"/>',
    '<span epub:type="pagebreak" id="page85" title="85"/>',
    '<span epub:type="pagebreak" id="page86" title="86"/>',
    '<span epub:type="pagebreak" id="page87" title="87"/>',
    '<span epub:type="pagebreak" id="page88" title="88"/>',
    '<span epub:type="pagebreak" id="page89" title="89"/>',
    '<span epub:type="pagebreak" id="page90" title="90"/>',
    '<span epub:type="pagebreak" id="page91" title="91"/>',
    '<span epub:type="pagebreak" id="page92" title="92"/>',
    '<span epub:type="pagebreak" id="page93" title="93"/>',
    '<span epub:type="pagebreak" id="page94" title="94"/>',
    '<span epub:type="pagebreak" id="page95" title="95"/>',
    '<span epub:type="pagebreak" id="page96" title="96"/>',
    '<span epub:type="pagebreak" id="page97" title="97"/>',
    '<span epub:type="pagebreak" id="page98" title="98"/>',
    '<span epub:type="pagebreak" id="page99" title="99"/>',
    '<span epub:type="pagebreak" id="page100" title="100"/>',
    '<span epub:type="pagebreak" id="page101" title="101"/>',
    '<span epub:type="pagebreak" id="page102" title="102"/>',
    '<span epub:type="pagebreak" id="page103" title="103"/>',
    '<span epub:type="pagebreak" id="page104" title="104"/>',
    '<span epub:type="pagebreak" id="page105" title="105"/>',
    '<span epub:type="pagebreak" id="page106" title="106"/>',
    '<span epub:type="pagebreak" id="page107" title="107"/>',
    '<span epub:type="pagebreak" id="page108" title="108"/>',
    '<span epub:type="pagebreak" id="page109" title="109"/>',
    '<span epub:type="pagebreak" id="page110" title="110"/>',
    '<span epub:type="pagebreak" id="page111" title="111"/>',
    '<span epub:type="pagebreak" id="page112" title="112"/>',
    '<span epub:type="pagebreak" id="page113" title="113"/>',
    '<span epub:type="pagebreak" id="page114" title="114"/>',
    '<span epub:type="pagebreak" id="page115" title="115"/>',
    '<span epub:type="pagebreak" id="page116" title="116"/>',
    '<span epub:type="pagebreak" id="page117" title="117"/>',
    '<span epub:type="pagebreak" id="page118" title="118"/>',
    '<span epub:type="pagebreak" id="page119" title="119"/>',
    '<span epub:type="pagebreak" id="page120" title="120"/>',
    '<span epub:type="pagebreak" id="page121" title="121"/>',
    '<span epub:type="pagebreak" id="page122" title="122"/>',
    '<span epub:type="pagebreak" id="page123" title="123"/>',
    '<span epub:type="pagebreak" id="page124" title="124"/>',
    '<span epub:type="pagebreak" id="page125" title="125"/>',
    '<span epub:type="pagebreak" id="page126" title="126"/>'


    ],
    firstSentences: [
    ' 1. Can We Speak and Think about God? 1',
    'My book Warranted Christian Belief1 came out more than a dozen years ',
    'speaking, to the old atheists (e.g., Bertrand Russell, C. D. Broad, and J. L. ',
    'go on to argue (1) that these criticisms, these claims that religious belief is ',
    'A third suggestion, owing to Sigmund Freud (1856-1939) and Karl ',
    'Of course, even if Christian belief can be warranted, it can still be ',
    'I argue in Chapter Ten that while evil constitutes a problem for believers, ',
    'Our question in this volume has to do with the justification or rationality ',
    'philosopher Immanuel Kant (1724-1804) in his monumental Critique of ',
    'selves, the world as it is in itself, and also the world of appearance, the ',
    'experience can be directly identified as that to which the term “God” ',
    'the Apostles’ Creed, for example — what they say can’t really be true. ',
    'engage in some kind of survey, looking at a lot of horses to see what pro',
    'Now many people concede that there is such a thing as Christian belief, but ',
    'it’s not possible to be a person without a body.2 Again, God is supposed to ',
    'The de jure objection is offered, second, by those who emphasize the ',
    'This is the claim that it is arrogant or egotistical to endorse or believe ',
    'to advance my career is wrong; and the more I think about it, the more ',
    'his opinions, and actions depending thereon?” In a classic text, he gives ',
    'believe or disbelieve as reason directs you. And if you don’t do that, then ',
    'But obviously you can’t have propositional evidence for everything ',
    'or incorrigible. Locke’s views here are an example of classical foundation-',
    'That’s a serious problem, then, for the justificationist objection to',
    'I look at the evidence for some proposition, and then decide to believe ',
    'tains many who do not believe as she does. She doesn’t believe on the basis ',
    'subterranean way that without evidence she isn’t justified; if so, this must ',
    'ulty or power by virtue of which human beings are able to do these things. ',
    'the self- feeling of the man who has either not yet found himself, or ',
    'Well, perhaps this grisly little tale doesn’t come to much as a serious ',
    'of mind. You can also be blinded by covetousness, love, fear, lust, anger, ',
    'this helplessness lasts throughout life made it necessary to cling to ',
    'The whole thing is so patently infantile, so incongruous with reality, ',
    'your belief was true, but didn’t constitute knowledge. What is needed, in ',
    'of the lungs, to provide oxygen; and so on. If the design is a good design, ',
    'question is produced by cognitive faculties whose purpose is that of pro-',
    'Now we are ready to return to the F&M complaint: this complaint is really ',
    'For since the creation of the world God’s invisible qualities ',
    'for a way in which theistic belief could have warrant. Once we see that ',
    'ceived in the things that have been made. So they are without excuse. ',
    'Calvin goes on to claim that many rejections of God, or attempts to do ',
    'a little maturity. My guess is Calvin thinks the same with respect to this ',
    'thing like an awareness of divine disapproval upon having done what is ',
    'accepted on the evidential basis of other propositions. The same goes for ',
    'enable us to have true beliefs about God; and when it functions properly, it ',
    'have horns. Your belief is false, but has a certain degree of warrant. You are ',
    'Now a proposition is probable, with respect to some condition, only ',
    'This isn’t certain; the argument is not deductively valid. It is abstractly ',
    'of blind evolutionary forces; you may think there is no God, and that we ',
    'a lot to say about religious belief — except, of course, for a number of ',
    'presence; perhaps this is how God has arranged for us to come to know ',
    'also be seen as resulting from wish- fulfillment — a result of the desire to ',
    'According to the Aquinas/Calvin (A/C) model, theistic belief (belief in ',
    'Calvinist in inspiration, but I shall develop it in my own way. I shall use ',
    'According to the extended A/C model, Christian belief does indeed have ',
    'present life and reaching fruition in the next) that involves a restoration ',
    'we human beings find ourselves from our very birth. A traditional Chris-',
    'I am inclined to seek first my own personal aggrandizement, bending all ',
    'enough: she sees what is right, but prefers what is wrong. Socrates fails ',
    'I recognize is the wrong thing, even though I don’t want to do the wrong ',
    'and educated twenty- first- century Christians who are entirely aware of all ',
    'second element of this three- tiered cognitive process: the presence and ',
    'But isn’t all this just endorsing a wholly outmoded and discredited ',
    'contumely that goes with the term? An argument of some kind against ',
    'Now faith is the substance of things hoped for, the evidence of ',
    'connection with this use that one thinks of ‘a leap of faith’, which is rather ',
    'God, and have been granted salvation” (Heidelberg Catechism A. 21) ',
    'for he is moved by the authority of divine teaching confirmed by miracles ',
    'reconciling the world to himself!” And I may also think something a bit ',
    'of what is proposed. Here Aquinas’s terms “invitation” and “instigation” ',
    'obligation — especially if it seems to you, after reflection, that the teaching ',
    'cess that produces these beliefs is specifically designed by God himself to ',
    'enlightened, have of the truth of the things of religion, is a kind of intu-',
    'beliefs have warrant for the believer swings free of those historical and ',
    'course, is there (on the model) any similarity from the outside. This is no ',
    'lieved by any reasonable person without one. . . . Whoever is moved ',
    'able to be aware of these truths. And if that is so, the natural thing to think ',
    'As we’ve seen, the extended A/C model shows how Christian belief can ',
    'contest, perhaps in that familiar self- deceived condition of really knowing, ',
    'Domine.1 Of the Holy Spirit, he says that “persistently boiling away and ',
    'The word in is well chosen and deserving of due attention. We do not ',
    'divine things” (p. 271). And love brings other affections in its train: “love ',
    'One thing have I desired of the Lord, that I will seek after; that I . . . ',
    'Of course you can’t; you remain unsatisfied. Jean- Paul Sartre says ',
    'benevolence,8 a completely other- regarding, magnanimous love in which ',
    'his love for us. It is, instead, a matter of God’s taking enormous pleasure, ',
    'This sealing, according to the model, consists in having the right sorts of ',
    'The extended Aquinas/Calvin (A/C) model is designed to show that and ',
    'true that this belief gets its warrant through religious experience? Maybe ',
    'ences include in their content beliefs that are probably false and in any ',
    '(or of my own guilt, or that I am in danger, or of the glorious beauty of the ',
    'would meet the conditions necessary and sufficient for having warrant: ',
    'wise — that is, given any course of sensuous imagery, affective experience, ',
    'proposition p, then that experience must be such that it (logically) cannot ',
    'doesn’t follow that you can’t tell by experience that there is a horse there. ',
    'But of course, even if Christian and theistic belief can have warrant, ',
    'So far I’ve argued that Christian belief — the full panoply of Christian ',
    'the basic way, as in the model, is for the most part irrational: “I conclude ',
    'experience; it also depends on what other beliefs I have, and how firmly I ',
    'for Christian belief. Finally, in Chapter Ten, I’ll consider what has often ',
    '‘historical biblical criticism’ — HBC for short. Scripture scholarship of ',
    'like a contemporary book on theology or philosophy. It isn’t a book full of ',
    'teachings of Scripture. (Calvin’s commentaries alone run to more than ',
    'that are inferred from premises coming from different parts of the Bible: ',
    'Traditional biblical commentary has been practiced from the beginning. ',
    'tual results” (p. 9); he intends his own contributions to be “scientifically ',
    'ever their backgrounds, spiritual experiences, or personal beliefs and ',
    'beyond creation and conservation. So taken, this principle implies that ',
    'involve any theological, religious, or metaphysical assumptions that  aren’t ',
    'able fully to comprehend, in divesting religion of its spiritual and heavenly ',
    '(Amanita muscaria). Still, the name ‘Christ’ isn’t empty: it is really a name ',
    'Troeltschians, however, apparently don’t offer any such good reasons for ',
    'Or consider John Meier’s monumental A Marginal Jew: Rethink-',
    'that Jesus was divine and that he rose from the dead. Hence, he will be ',
    'Historical biblical criticism, as I argued, doesn’t or at least doesn’t auto',
    'exclusivism] has become unacceptable to all except a minority of dog-',
    'our question, that is, is whether I have a defeater for my Christian belief in ',
    '— fail to believe something that is true, deep, and important. Of course she ',
    'he took the poor man’s single ewe lamb, slaughtered it, and served it to his ',
    'in these beliefs. (And here we have a way in which the epistemologist can ',
    'of the enormous variety of human religious responses does seem to reduce ',
    'we come to apprehend (1) and (2). In this way knowledge of the facts of ',
    'I turn finally to the most formidable candidate for a defeater for theistic ',
    'tempted to doubt the existence or even the goodness of God; nevertheless ',
    'have suggested, does knowledge of the facts of evil provide a defeater for ',
    'another turtle, and so on, so that it’s turtles all the way down; nevertheless ',
    'The reason, of course, is that this belief doesn’t depend, for its warrant, on ',
    'But perhaps that’s not the only realistic reaction here: perhaps I could ',
    'away, to avert his eyes from the abomination of suffering, to take refuge in ',
    'On the A/C model, therefore, the facts of evil do not constitute any sort ',
    'how my suffering contributes to some good?” But then I think of the divine ',
    'letter from Guido de Bres (author of the Belgic Confession, 1561) to his ',
    'I should think the right answer is “Probably not.” Consider a person ',
    'Chapter Two I distinguished de jure from de facto objections to Christian '
    ]
}