module.exports = {

    pageNumbers: ["<span epub:type=\"pagebreak\" id=\"page87\" title=\"87\"/>",
"<span epub:type=\"pagebreak\" id=\"page88\" title=\"88\"/>",
"<span epub:type=\"pagebreak\" id=\"page89\" title=\"89\"/>",
"<span epub:type=\"pagebreak\" id=\"page90\" title=\"90\"/>",
"<span epub:type=\"pagebreak\" id=\"page91\" title=\"91\"/>",
"<span epub:type=\"pagebreak\" id=\"page92\" title=\"92\"/>",
"<span epub:type=\"pagebreak\" id=\"page93\" title=\"93\"/>",
"<span epub:type=\"pagebreak\" id=\"page94\" title=\"94\"/>",
"<span epub:type=\"pagebreak\" id=\"page95\" title=\"95\"/>",
"<span epub:type=\"pagebreak\" id=\"page96\" title=\"96\"/>",
"<span epub:type=\"pagebreak\" id=\"pagex\" title=\"x\"/>",
"<span epub:type=\"pagebreak\" id=\"page97\" title=\"97\"/>",
"<span epub:type=\"pagebreak\" id=\"page98\" title=\"98\"/>",
"<span epub:type=\"pagebreak\" id=\"page99\" title=\"99\"/>",
"<span epub:type=\"pagebreak\" id=\"page100\" title=\"100\"/>",
"<span epub:type=\"pagebreak\" id=\"page101\" title=\"101\"/>",
"<span epub:type=\"pagebreak\" id=\"page102\" title=\"102\"/>"
,"<span epub:type=\"pagebreak\" id=\"page103\" title=\"103\"/>",
"<span epub:type=\"pagebreak\" id=\"page104\" title=\"104\"/>",
"<span epub:type=\"pagebreak\" id=\"page105\" title=\"105\"/>",
"<span epub:type=\"pagebreak\" id=\"page106\" title=\"106\"/>",
"<span epub:type=\"pagebreak\" id=\"pagexi\" title=\"xi\"/>"
,"<span epub:type=\"pagebreak\" id=\"page107\" title=\"107\"/>",
"<span epub:type=\"pagebreak\" id=\"page108\" title=\"108\"/>",
"<span epub:type=\"pagebreak\" id=\"page109\" title=\"109\"/>",
"<span epub:type=\"pagebreak\" id=\"page110\" title=\"110\"/>",
"<span epub:type=\"pagebreak\" id=\"page111\" title=\"111\"/>"
,"<span epub:type=\"pagebreak\" id=\"page112\" title=\"112\"/>",
"<span epub:type=\"pagebreak\" id=\"page113\" title=\"113\"/>",
"<span epub:type=\"pagebreak\" id=\"page114\" title=\"114\"/>",
"<span epub:type=\"pagebreak\" id=\"page115\" title=\"115\"/>",
"<span epub:type=\"pagebreak\" id=\"page116\" title=\"116\"/>"
,"<span epub:type=\"pagebreak\" id=\"page117\" title=\"117\"/>",
"<span epub:type=\"pagebreak\" id=\"page118\" title=\"118\"/>",
"<span epub:type=\"pagebreak\" id=\"page119\" title=\"119\"/>",
"<span epub:type=\"pagebreak\" id=\"page120\" title=\"120\"/>",
"<span epub:type=\"pagebreak\" id=\"page121\" title=\"121\"/>"
,"<span epub:type=\"pagebreak\" id=\"page124\" title=\"124\"/>",
"<span epub:type=\"pagebreak\" id=\"page125\" title=\"125\"/>",
"<span epub:type=\"pagebreak\" id=\"page126\" title=\"126\"/>",
"<span epub:type=\"pagebreak\" id=\"page127\" title=\"127\"/>",
"<span epub:type=\"pagebreak\" id=\"page128\" title=\"128\"/>"
,"<span epub:type=\"pagebreak\" id=\"page129\" title=\"129\"/>",
"<span epub:type=\"pagebreak\" id=\"page130\" title=\"130\"/>",
"<span epub:type=\"pagebreak\" id=\"page131\" title=\"131\"/>",
"<span epub:type=\"pagebreak\" id=\"page132\" title=\"132\"/>",
"<span epub:type=\"pagebreak\" id=\"page133\" title=\"133\"/>"
,"<span epub:type=\"pagebreak\" id=\"page134\" title=\"134\"/>",
"<span epub:type=\"pagebreak\" id=\"page135\" title=\"135\"/>",
"<span epub:type=\"pagebreak\" id=\"page136\" title=\"136\"/>",
"<span epub:type=\"pagebreak\" id=\"page2\" title=\"2\"/>",
"<span epub:type=\"pagebreak\" id=\"page137\" title=\"137\"/>"
,"<span epub:type=\"pagebreak\" id=\"page138\" title=\"138\"/>",
"<span epub:type=\"pagebreak\" id=\"page139\" title=\"139\"/>",
"<span epub:type=\"pagebreak\" id=\"page140\" title=\"140\"/>",
"<span epub:type=\"pagebreak\" id=\"page141\" title=\"141\"/>",
"<span epub:type=\"pagebreak\" id=\"page142\" title=\"142\"/>"
,"<span epub:type=\"pagebreak\" id=\"page143\" title=\"143\"/>",
"<span epub:type=\"pagebreak\" id=\"page144\" title=\"144\"/>",
"<span epub:type=\"pagebreak\" id=\"page145\" title=\"145\"/>",
"<span epub:type=\"pagebreak\" id=\"page146\" title=\"146\"/>",
"<span epub:type=\"pagebreak\" id=\"page3\" title=\"3\"/>"
,"<span epub:type=\"pagebreak\" id=\"page147\" title=\"147\"/>",
"<span epub:type=\"pagebreak\" id=\"page148\" title=\"148\"/>",
"<span epub:type=\"pagebreak\" id=\"page149\" title=\"149\"/>",
"<span epub:type=\"pagebreak\" id=\"page150\" title=\"150\"/>",
"<span epub:type=\"pagebreak\" id=\"page151\" title=\"151\"/>"
,"<span epub:type=\"pagebreak\" id=\"page152\" title=\"152\"/>",
"<span epub:type=\"pagebreak\" id=\"page153\" title=\"153\"/>",
"<span epub:type=\"pagebreak\" id=\"page154\" title=\"154\"/>",
"<span epub:type=\"pagebreak\" id=\"page155\" title=\"155\"/>",
"<span epub:type=\"pagebreak\" id=\"page156\" title=\"156\"/>"
,"<span epub:type=\"pagebreak\" id=\"page4\" title=\"4\"/>",
"<span epub:type=\"pagebreak\" id=\"page157\" title=\"157\"/>",
"<span epub:type=\"pagebreak\" id=\"page158\" title=\"158\"/>",
"<span epub:type=\"pagebreak\" id=\"page159\" title=\"159\"/>",
"<span epub:type=\"pagebreak\" id=\"page160\" title=\"160\"/>"
,"<span epub:type=\"pagebreak\" id=\"page161\" title=\"161\"/>",
"<span epub:type=\"pagebreak\" id=\"page162\" title=\"162\"/>",
"<span epub:type=\"pagebreak\" id=\"page163\" title=\"163\"/>",
"<span epub:type=\"pagebreak\" id=\"page164\" title=\"164\"/>",
"<span epub:type=\"pagebreak\" id=\"page165\" title=\"165\"/>"
,"<span epub:type=\"pagebreak\" id=\"page166\" title=\"166\"/>",
"<span epub:type=\"pagebreak\" id=\"page5\" title=\"5\"/>",
"<span epub:type=\"pagebreak\" id=\"page167\" title=\"167\"/>",
"<span epub:type=\"pagebreak\" id=\"page168\" title=\"168\"/>",
"<span epub:type=\"pagebreak\" id=\"page169\" title=\"169\"/>"
,"<span epub:type=\"pagebreak\" id=\"page170\" title=\"170\"/>",
"<span epub:type=\"pagebreak\" id=\"page171\" title=\"171\"/>",
"<span epub:type=\"pagebreak\" id=\"page174\" title=\"174\"/>",
"<span epub:type=\"pagebreak\" id=\"page175\" title=\"175\"/>",
"<span epub:type=\"pagebreak\" id=\"page176\" title=\"176\"/>"
,"<span epub:type=\"pagebreak\" id=\"page6\" title=\"6\"/>",
"<span epub:type=\"pagebreak\" id=\"page177\" title=\"177\"/>",
"<span epub:type=\"pagebreak\" id=\"page178\" title=\"178\"/>",
"<span epub:type=\"pagebreak\" id=\"page179\" title=\"179\"/>",
"<span epub:type=\"pagebreak\" id=\"page180\" title=\"180\"/>"
,"<span epub:type=\"pagebreak\" id=\"page181\" title=\"181\"/>",
"<span epub:type=\"pagebreak\" id=\"page182\" title=\"182\"/>",
"<span epub:type=\"pagebreak\" id=\"page183\" title=\"183\"/>",
"<span epub:type=\"pagebreak\" id=\"page184\" title=\"184\"/>",
"<span epub:type=\"pagebreak\" id=\"page185\" title=\"185\"/>"
,"<span epub:type=\"pagebreak\" id=\"page186\" title=\"186\"/>",
"<span epub:type=\"pagebreak\" id=\"page7\" title=\"7\"/>",
"<span epub:type=\"pagebreak\" id=\"page187\" title=\"187\"/>",
"<span epub:type=\"pagebreak\" id=\"page188\" title=\"188\"/>",
"<span epub:type=\"pagebreak\" id=\"page189\" title=\"189\"/>"
,"<span epub:type=\"pagebreak\" id=\"page190\" title=\"190\"/>",
"<span epub:type=\"pagebreak\" id=\"page191\" title=\"191\"/>",
"<span epub:type=\"pagebreak\" id=\"page192\" title=\"192\"/>",
"<span epub:type=\"pagebreak\" id=\"page193\" title=\"193\"/>",
"<span epub:type=\"pagebreak\" id=\"page194\" title=\"194\"/>"
,"<span epub:type=\"pagebreak\" id=\"page195\" title=\"195\"/>",
"<span epub:type=\"pagebreak\" id=\"page196\" title=\"196\"/>",
"<span epub:type=\"pagebreak\" id=\"page8\" title=\"8\"/>",
"<span epub:type=\"pagebreak\" id=\"page197\" title=\"197\"/>",
"<span epub:type=\"pagebreak\" id=\"page198\" title=\"198\"/>"
,"<span epub:type=\"pagebreak\" id=\"page199\" title=\"199\"/>",
"<span epub:type=\"pagebreak\" id=\"page200\" title=\"200\"/>",
"<span epub:type=\"pagebreak\" id=\"page201\" title=\"201\"/>",
"<span epub:type=\"pagebreak\" id=\"page202\" title=\"202\"/>",
"<span epub:type=\"pagebreak\" id=\"page203\" title=\"203\"/>"
,"<span epub:type=\"pagebreak\" id=\"page204\" title=\"204\"/>",
"<span epub:type=\"pagebreak\" id=\"page205\" title=\"205\"/>",
"<span epub:type=\"pagebreak\" id=\"page206\" title=\"206\"/>",
"<span epub:type=\"pagebreak\" id=\"page9\" title=\"9\"/>",
"<span epub:type=\"pagebreak\" id=\"page207\" title=\"207\"/>"
,"<span epub:type=\"pagebreak\" id=\"page210\" title=\"210\"/>",
"<span epub:type=\"pagebreak\" id=\"page211\" title=\"211\"/>",
"<span epub:type=\"pagebreak\" id=\"page212\" title=\"212\"/>",
"<span epub:type=\"pagebreak\" id=\"page213\" title=\"213\"/>",
"<span epub:type=\"pagebreak\" id=\"page214\" title=\"214\"/>"
,"<span epub:type=\"pagebreak\" id=\"page215\" title=\"215\"/>",
"<span epub:type=\"pagebreak\" id=\"page216\" title=\"216\"/>",
"<span epub:type=\"pagebreak\" id=\"page10\" title=\"10\"/>",
"<span epub:type=\"pagebreak\" id=\"page217\" title=\"217\"/>",
"<span epub:type=\"pagebreak\" id=\"page218\" title=\"218\"/>"
,"<span epub:type=\"pagebreak\" id=\"page219\" title=\"219\"/>",
"<span epub:type=\"pagebreak\" id=\"page220\" title=\"220\"/>",
"<span epub:type=\"pagebreak\" id=\"page221\" title=\"221\"/>",
"<span epub:type=\"pagebreak\" id=\"page222\" title=\"222\"/>",
"<span epub:type=\"pagebreak\" id=\"page223\" title=\"223\"/>"
,"<span epub:type=\"pagebreak\" id=\"page224\" title=\"224\"/>",
"<span epub:type=\"pagebreak\" id=\"page225\" title=\"225\"/>",
"<span epub:type=\"pagebreak\" id=\"page226\" title=\"226\"/>",
"<span epub:type=\"pagebreak\" id=\"page11\" title=\"11\"/>",
"<span epub:type=\"pagebreak\" id=\"page227\" title=\"227\"/>"
,"<span epub:type=\"pagebreak\" id=\"page228\" title=\"228\"/>",
"<span epub:type=\"pagebreak\" id=\"page229\" title=\"229\"/>",
"<span epub:type=\"pagebreak\" id=\"page230\" title=\"230\"/>",
"<span epub:type=\"pagebreak\" id=\"page231\" title=\"231\"/>",
"<span epub:type=\"pagebreak\" id=\"page232\" title=\"232\"/>"
,"<span epub:type=\"pagebreak\" id=\"page233\" title=\"233\"/>",
"<span epub:type=\"pagebreak\" id=\"page234\" title=\"234\"/>",
"<span epub:type=\"pagebreak\" id=\"page235\" title=\"235\"/>",
"<span epub:type=\"pagebreak\" id=\"page236\" title=\"236\"/>",
"<span epub:type=\"pagebreak\" id=\"page12\" title=\"12\"/>"
,"<span epub:type=\"pagebreak\" id=\"page237\" title=\"237\"/>",
"<span epub:type=\"pagebreak\" id=\"page238\" title=\"238\"/>",
"<span epub:type=\"pagebreak\" id=\"page239\" title=\"239\"/>",
"<span epub:type=\"pagebreak\" id=\"page240\" title=\"240\"/>",
"<span epub:type=\"pagebreak\" id=\"page241\" title=\"241\"/>"
,"<span epub:type=\"pagebreak\" id=\"page242\" title=\"242\"/>",
"<span epub:type=\"pagebreak\" id=\"page243\" title=\"243\"/>",
"<span epub:type=\"pagebreak\" id=\"page244\" title=\"244\"/>",
"<span epub:type=\"pagebreak\" id=\"page245\" title=\"245\"/>",
"<span epub:type=\"pagebreak\" id=\"page246\" title=\"246\"/>"
,"<span epub:type=\"pagebreak\" id=\"page13\" title=\"13\"/>",
"<span epub:type=\"pagebreak\" id=\"page247\" title=\"247\"/>",
"<span epub:type=\"pagebreak\" id=\"page248\" title=\"248\"/>",
"<span epub:type=\"pagebreak\" id=\"page249\" title=\"249\"/>",
"<span epub:type=\"pagebreak\" id=\"page250\" title=\"250\"/>"
,"<span epub:type=\"pagebreak\" id=\"page251\" title=\"251\"/>",
"<span epub:type=\"pagebreak\" id=\"page252\" title=\"252\"/>",
"<span epub:type=\"pagebreak\" id=\"page253\" title=\"253\"/>",
"<span epub:type=\"pagebreak\" id=\"page254\" title=\"254\"/>",
"<span epub:type=\"pagebreak\" id=\"page255\" title=\"255\"/>"
,"<span epub:type=\"pagebreak\" id=\"page14\" title=\"14\"/>",
"<span epub:type=\"pagebreak\" id=\"page258\" title=\"258\"/>",
"<span epub:type=\"pagebreak\" id=\"page259\" title=\"259\"/>",
"<span epub:type=\"pagebreak\" id=\"page260\" title=\"260\"/>",
"<span epub:type=\"pagebreak\" id=\"page261\" title=\"261\"/>"
,"<span epub:type=\"pagebreak\" id=\"page262\" title=\"262\"/>",
"<span epub:type=\"pagebreak\" id=\"page263\" title=\"263\"/>",
"<span epub:type=\"pagebreak\" id=\"page264\" title=\"264\"/>",
"<span epub:type=\"pagebreak\" id=\"page265\" title=\"265\"/>",
"<span epub:type=\"pagebreak\" id=\"page266\" title=\"266\"/>"
,"<span epub:type=\"pagebreak\" id=\"page15\" title=\"15\"/>",
"<span epub:type=\"pagebreak\" id=\"page267\" title=\"267\"/>",
"<span epub:type=\"pagebreak\" id=\"page268\" title=\"268\"/>",
"<span epub:type=\"pagebreak\" id=\"page269\" title=\"269\"/>",
"<span epub:type=\"pagebreak\" id=\"page270\" title=\"270\"/>"
,"<span epub:type=\"pagebreak\" id=\"page271\" title=\"271\"/>",
"<span epub:type=\"pagebreak\" id=\"page272\" title=\"272\"/>",
"<span epub:type=\"pagebreak\" id=\"page273\" title=\"273\"/>",
"<span epub:type=\"pagebreak\" id=\"page274\" title=\"274\"/>",
"<span epub:type=\"pagebreak\" id=\"page275\" title=\"275\"/>"
,"<span epub:type=\"pagebreak\" id=\"page276\" title=\"276\"/>",
"<span epub:type=\"pagebreak\" id=\"page16\" title=\"16\"/>",
"<span epub:type=\"pagebreak\" id=\"page277\" title=\"277\"/>",
"<span epub:type=\"pagebreak\" id=\"page278\" title=\"278\"/>",
"<span epub:type=\"pagebreak\" id=\"page279\" title=\"279\"/>"
,"<span epub:type=\"pagebreak\" id=\"page280\" title=\"280\"/>",
"<span epub:type=\"pagebreak\" id=\"page281\" title=\"281\"/>",
"<span epub:type=\"pagebreak\" id=\"page282\" title=\"282\"/>",
"<span epub:type=\"pagebreak\" id=\"page283\" title=\"283\"/>",
"<span epub:type=\"pagebreak\" id=\"page284\" title=\"284\"/>"
,"<span epub:type=\"pagebreak\" id=\"page285\" title=\"285\"/>",
"<span epub:type=\"pagebreak\" id=\"page286\" title=\"286\"/>",
"<span epub:type=\"pagebreak\" id=\"page17\" title=\"17\"/>",
"<span epub:type=\"pagebreak\" id=\"page287\" title=\"287\"/>",
"<span epub:type=\"pagebreak\" id=\"page288\" title=\"288\"/>"
,"<span epub:type=\"pagebreak\" id=\"page289\" title=\"289\"/>",
"<span epub:type=\"pagebreak\" id=\"page290\" title=\"290\"/>",
"<span epub:type=\"pagebreak\" id=\"page291\" title=\"291\"/>",
"<span epub:type=\"pagebreak\" id=\"page292\" title=\"292\"/>",
"<span epub:type=\"pagebreak\" id=\"page293\" title=\"293\"/>"
,"<span epub:type=\"pagebreak\" id=\"page294\" title=\"294\"/>",
"<span epub:type=\"pagebreak\" id=\"page295\" title=\"295\"/>",
"<span epub:type=\"pagebreak\" id=\"page296\" title=\"296\"/>",
"<span epub:type=\"pagebreak\" id=\"page18\" title=\"18\"/>",
"<span epub:type=\"pagebreak\" id=\"page297\" title=\"297\"/>"
,"<span epub:type=\"pagebreak\" id=\"page298\" title=\"298\"/>",
"<span epub:type=\"pagebreak\" id=\"page299\" title=\"299\"/>",
"<span epub:type=\"pagebreak\" id=\"page300\" title=\"300\"/>",
"<span epub:type=\"pagebreak\" id=\"page301\" title=\"301\"/>",
"<span epub:type=\"pagebreak\" id=\"page302\" title=\"302\"/>"
,"<span epub:type=\"pagebreak\" id=\"page303\" title=\"303\"/>",
"<span epub:type=\"pagebreak\" id=\"page304\" title=\"304\"/>",
"<span epub:type=\"pagebreak\" id=\"page305\" title=\"305\"/>",
"<span epub:type=\"pagebreak\" id=\"page306\" title=\"306\"/>",
"<span epub:type=\"pagebreak\" id=\"page19\" title=\"19\"/>"
,"<span epub:type=\"pagebreak\" id=\"page307\" title=\"307\"/>",
"<span epub:type=\"pagebreak\" id=\"page308\" title=\"308\"/>",
"<span epub:type=\"pagebreak\" id=\"page309\" title=\"309\"/>",
"<span epub:type=\"pagebreak\" id=\"page310\" title=\"310\"/>",
"<span epub:type=\"pagebreak\" id=\"page311\" title=\"311\"/>"
,"<span epub:type=\"pagebreak\" id=\"page312\" title=\"312\"/>",
"<span epub:type=\"pagebreak\" id=\"page313\" title=\"313\"/>",
"<span epub:type=\"pagebreak\" id=\"page314\" title=\"314\"/>",
"<span epub:type=\"pagebreak\" id=\"page315\" title=\"315\"/>",
"<span epub:type=\"pagebreak\" id=\"page316\" title=\"316\"/>"
,"<span epub:type=\"pagebreak\" id=\"page20\" title=\"20\"/>",
"<span epub:type=\"pagebreak\" id=\"page317\" title=\"317\"/>",
"<span epub:type=\"pagebreak\" id=\"page318\" title=\"318\"/>",
"<span epub:type=\"pagebreak\" id=\"page319\" title=\"319\"/>",
"<span epub:type=\"pagebreak\" id=\"page320\" title=\"320\"/>"
,"<span epub:type=\"pagebreak\" id=\"page321\" title=\"321\"/>",
"<span epub:type=\"pagebreak\" id=\"page322\" title=\"322\"/>",
"<span epub:type=\"pagebreak\" id=\"page323\" title=\"323\"/>",
"<span epub:type=\"pagebreak\" id=\"page324\" title=\"324\"/>",
"<span epub:type=\"pagebreak\" id=\"page326\" title=\"326\"/>"
,"<span epub:type=\"pagebreak\" id=\"page21\" title=\"21\"/>",
"<span epub:type=\"pagebreak\" id=\"page327\" title=\"327\"/>",
"<span epub:type=\"pagebreak\" id=\"page328\" title=\"328\"/>",
"<span epub:type=\"pagebreak\" id=\"page329\" title=\"329\"/>",
"<span epub:type=\"pagebreak\" id=\"page330\" title=\"330\"/>"
,"<span epub:type=\"pagebreak\" id=\"page331\" title=\"331\"/>",
"<span epub:type=\"pagebreak\" id=\"page332\" title=\"332\"/>",
"<span epub:type=\"pagebreak\" id=\"page333\" title=\"333\"/>",
"<span epub:type=\"pagebreak\" id=\"page334\" title=\"334\"/>",
"<span epub:type=\"pagebreak\" id=\"page335\" title=\"335\"/>"
,"<span epub:type=\"pagebreak\" id=\"page336\" title=\"336\"/>",
"<span epub:type=\"pagebreak\" id=\"page22\" title=\"22\"/>",
"<span epub:type=\"pagebreak\" id=\"page337\" title=\"337\"/>",
"<span epub:type=\"pagebreak\" id=\"page338\" title=\"338\"/>",
"<span epub:type=\"pagebreak\" id=\"page339\" title=\"339\"/>"
,"<span epub:type=\"pagebreak\" id=\"page340\" title=\"340\"/>",
"<span epub:type=\"pagebreak\" id=\"page341\" title=\"341\"/>",
"<span epub:type=\"pagebreak\" id=\"page342\" title=\"342\"/>",
"<span epub:type=\"pagebreak\" id=\"page343\" title=\"343\"/>",
"<span epub:type=\"pagebreak\" id=\"page344\" title=\"344\"/>"
,"<span epub:type=\"pagebreak\" id=\"page345\" title=\"345\"/>",
"<span epub:type=\"pagebreak\" id=\"page346\" title=\"346\"/>",
"<span epub:type=\"pagebreak\" id=\"page23\" title=\"23\"/>",
"<span epub:type=\"pagebreak\" id=\"page347\" title=\"347\"/>",
"<span epub:type=\"pagebreak\" id=\"page348\" title=\"348\"/>"
,"<span epub:type=\"pagebreak\" id=\"page349\" title=\"349\"/>",
"<span epub:type=\"pagebreak\" id=\"page350\" title=\"350\"/>",
"<span epub:type=\"pagebreak\" id=\"page351\" title=\"351\"/>",
"<span epub:type=\"pagebreak\" id=\"page352\" title=\"352\"/>",
"<span epub:type=\"pagebreak\" id=\"page353\" title=\"353\"/>"
,"<span epub:type=\"pagebreak\" id=\"page354\" title=\"354\"/>",
"<span epub:type=\"pagebreak\" id=\"page355\" title=\"355\"/>",
"<span epub:type=\"pagebreak\" id=\"page356\" title=\"356\"/>",
"<span epub:type=\"pagebreak\" id=\"page24\" title=\"24\"/>",
"<span epub:type=\"pagebreak\" id=\"page357\" title=\"357\"/>"
,"<span epub:type=\"pagebreak\" id=\"page358\" title=\"358\"/>",
"<span epub:type=\"pagebreak\" id=\"page359\" title=\"359\"/>",
"<span epub:type=\"pagebreak\" id=\"page360\" title=\"360\"/>",
"<span epub:type=\"pagebreak\" id=\"page361\" title=\"361\"/>",
"<span epub:type=\"pagebreak\" id=\"page362\" title=\"362\"/>"
,"<span epub:type=\"pagebreak\" id=\"page363\" title=\"363\"/>",
"<span epub:type=\"pagebreak\" id=\"page364\" title=\"364\"/>",
"<span epub:type=\"pagebreak\" id=\"page365\" title=\"365\"/>",
"<span epub:type=\"pagebreak\" id=\"page366\" title=\"366\"/>",
"<span epub:type=\"pagebreak\" id=\"page367\" title=\"367\"/>"
,"<span epub:type=\"pagebreak\" id=\"page368\" title=\"368\"/>",
"<span epub:type=\"pagebreak\" id=\"page369\" title=\"369\"/>",
"<span epub:type=\"pagebreak\" id=\"page370\" title=\"370\"/>",
"<span epub:type=\"pagebreak\" id=\"page371\" title=\"371\"/>",
"<span epub:type=\"pagebreak\" id=\"page372\" title=\"372\"/>"
,"<span epub:type=\"pagebreak\" id=\"page373\" title=\"373\"/>",
"<span epub:type=\"pagebreak\" id=\"page376\" title=\"376\"/>",
"<span epub:type=\"pagebreak\" id=\"page26\" title=\"26\"/>",
"<span epub:type=\"pagebreak\" id=\"page377\" title=\"377\"/>",
"<span epub:type=\"pagebreak\" id=\"page378\" title=\"378\"/>"
,"<span epub:type=\"pagebreak\" id=\"page379\" title=\"379\"/>",
"<span epub:type=\"pagebreak\" id=\"page380\" title=\"380\"/>",
"<span epub:type=\"pagebreak\" id=\"page381\" title=\"381\"/>",
"<span epub:type=\"pagebreak\" id=\"page382\" title=\"382\"/>",
"<span epub:type=\"pagebreak\" id=\"page383\" title=\"383\"/>"
,"<span epub:type=\"pagebreak\" id=\"page384\" title=\"384\"/>",
"<span epub:type=\"pagebreak\" id=\"page385\" title=\"385\"/>",
"<span epub:type=\"pagebreak\" id=\"page386\" title=\"386\"/>",
"<span epub:type=\"pagebreak\" id=\"page27\" title=\"27\"/>",
"<span epub:type=\"pagebreak\" id=\"page387\" title=\"387\"/>"
,"<span epub:type=\"pagebreak\" id=\"page388\" title=\"388\"/>",
"<span epub:type=\"pagebreak\" id=\"page389\" title=\"389\"/>",
"<span epub:type=\"pagebreak\" id=\"page390\" title=\"390\"/>",
"<span epub:type=\"pagebreak\" id=\"page391\" title=\"391\"/>",
"<span epub:type=\"pagebreak\" id=\"page392\" title=\"392\"/>"
,"<span epub:type=\"pagebreak\" id=\"page393\" title=\"393\"/>",
"<span epub:type=\"pagebreak\" id=\"page394\" title=\"394\"/>",
"<span epub:type=\"pagebreak\" id=\"page395\" title=\"395\"/>",
"<span epub:type=\"pagebreak\" id=\"page396\" title=\"396\"/>",
"<span epub:type=\"pagebreak\" id=\"page28\" title=\"28\"/>"
,"<span epub:type=\"pagebreak\" id=\"page397\" title=\"397\"/>",
"<span epub:type=\"pagebreak\" id=\"page398\" title=\"398\"/>",
"<span epub:type=\"pagebreak\" id=\"page399\" title=\"399\"/>",
"<span epub:type=\"pagebreak\" id=\"page400\" title=\"400\"/>",
"<span epub:type=\"pagebreak\" id=\"page402\" title=\"402\"/>"
,"<span epub:type=\"pagebreak\" id=\"page403\" title=\"403\"/>",
"<span epub:type=\"pagebreak\" id=\"page404\" title=\"404\"/>",
"<span epub:type=\"pagebreak\" id=\"page405\" title=\"405\"/>",
"<span epub:type=\"pagebreak\" id=\"page406\" title=\"406\"/>",
"<span epub:type=\"pagebreak\" id=\"page29\" title=\"29\"/>"
,"<span epub:type=\"pagebreak\" id=\"page407\" title=\"407\"/>",
"<span epub:type=\"pagebreak\" id=\"page408\" title=\"408\"/>",
"<span epub:type=\"pagebreak\" id=\"page409\" title=\"409\"/>",
"<span epub:type=\"pagebreak\" id=\"page410\" title=\"410\"/>",
"<span epub:type=\"pagebreak\" id=\"page411\" title=\"411\"/>"
,"<span epub:type=\"pagebreak\" id=\"page412\" title=\"412\"/>",
"<span epub:type=\"pagebreak\" id=\"page413\" title=\"413\"/>",
"<span epub:type=\"pagebreak\" id=\"page414\" title=\"414\"/>",
"<span epub:type=\"pagebreak\" id=\"page415\" title=\"415\"/>",
"<span epub:type=\"pagebreak\" id=\"page416\" title=\"416\"/>"
,"<span epub:type=\"pagebreak\" id=\"page30\" title=\"30\"/>",
"<span epub:type=\"pagebreak\" id=\"page417\" title=\"417\"/>",
"<span epub:type=\"pagebreak\" id=\"page418\" title=\"418\"/>",
"<span epub:type=\"pagebreak\" id=\"page419\" title=\"419\"/>",
"<span epub:type=\"pagebreak\" id=\"page420\" title=\"420\"/>"
,"<span epub:type=\"pagebreak\" id=\"page421\" title=\"421\"/>",
"<span epub:type=\"pagebreak\" id=\"page422\" title=\"422\"/>",
"<span epub:type=\"pagebreak\" id=\"page423\" title=\"423\"/>",
"<span epub:type=\"pagebreak\" id=\"page424\" title=\"424\"/>",
"<span epub:type=\"pagebreak\" id=\"page425\" title=\"425\"/>"
,"<span epub:type=\"pagebreak\" id=\"page426\" title=\"426\"/>",
"<span epub:type=\"pagebreak\" id=\"page31\" title=\"31\"/>",
"<span epub:type=\"pagebreak\" id=\"page427\" title=\"427\"/>",
"<span epub:type=\"pagebreak\" id=\"page428\" title=\"428\"/>",
"<span epub:type=\"pagebreak\" id=\"page429\" title=\"429\"/>"
,"<span epub:type=\"pagebreak\" id=\"page430\" title=\"430\"/>",
"<span epub:type=\"pagebreak\" id=\"page431\" title=\"431\"/>",
"<span epub:type=\"pagebreak\" id=\"page432\" title=\"432\"/>",
"<span epub:type=\"pagebreak\" id=\"page433\" title=\"433\"/>",
"<span epub:type=\"pagebreak\" id=\"page434\" title=\"434\"/>"
,"<span epub:type=\"pagebreak\" id=\"page435\" title=\"435\"/>",
"<span epub:type=\"pagebreak\" id=\"page436\" title=\"436\"/>",
"<span epub:type=\"pagebreak\" id=\"page32\" title=\"32\"/>",
"<span epub:type=\"pagebreak\" id=\"page437\" title=\"437\"/>",
"<span epub:type=\"pagebreak\" id=\"page438\" title=\"438\"/>"
,"<span epub:type=\"pagebreak\" id=\"page439\" title=\"439\"/>",
"<span epub:type=\"pagebreak\" id=\"page440\" title=\"440\"/>",
"<span epub:type=\"pagebreak\" id=\"page441\" title=\"441\"/>",
"<span epub:type=\"pagebreak\" id=\"page442\" title=\"442\"/>",
"<span epub:type=\"pagebreak\" id=\"page443\" title=\"443\"/>"
,"<span epub:type=\"pagebreak\" id=\"page444\" title=\"444\"/>",
"<span epub:type=\"pagebreak\" id=\"page445\" title=\"445\"/>",
"<span epub:type=\"pagebreak\" id=\"page446\" title=\"446\"/>",
"<span epub:type=\"pagebreak\" id=\"page33\" title=\"33\"/>",
"<span epub:type=\"pagebreak\" id=\"page447\" title=\"447\"/>"
,"<span epub:type=\"pagebreak\" id=\"page448\" title=\"448\"/>",
"<span epub:type=\"pagebreak\" id=\"page449\" title=\"449\"/>",
"<span epub:type=\"pagebreak\" id=\"page450\" title=\"450\"/>",
"<span epub:type=\"pagebreak\" id=\"page451\" title=\"451\"/>",
"<span epub:type=\"pagebreak\" id=\"page452\" title=\"452\"/>"
,"<span epub:type=\"pagebreak\" id=\"page453\" title=\"453\"/>",
"<span epub:type=\"pagebreak\" id=\"page454\" title=\"454\"/>",
"<span epub:type=\"pagebreak\" id=\"page455\" title=\"455\"/>",
"<span epub:type=\"pagebreak\" id=\"page456\" title=\"456\"/>",
"<span epub:type=\"pagebreak\" id=\"page34\" title=\"34\"/>"
,"<span epub:type=\"pagebreak\" id=\"page457\" title=\"457\"/>",
"<span epub:type=\"pagebreak\" id=\"page458\" title=\"458\"/>",
"<span epub:type=\"pagebreak\" id=\"page460\" title=\"460\"/>",
"<span epub:type=\"pagebreak\" id=\"page461\" title=\"461\"/>",
"<span epub:type=\"pagebreak\" id=\"page462\" title=\"462\"/>"
,"<span epub:type=\"pagebreak\" id=\"page35\" title=\"35\"/>",
"<span epub:type=\"pagebreak\" id=\"page467\" title=\"467\"/>",
"<span epub:type=\"pagebreak\" id=\"page36\" title=\"36\"/>",
"<span epub:type=\"pagebreak\" id=\"page37\" title=\"37\"/>",
"<span epub:type=\"pagebreak\" id=\"page38\" title=\"38\"/>",
"<span epub:type=\"pagebreak\" id=\"page39\" title=\"39\"/>",
"<span epub:type=\"pagebreak\" id=\"page40\" title=\"40\"/>",
"<span epub:type=\"pagebreak\" id=\"page41\" title=\"41\"/>",
"<span epub:type=\"pagebreak\" id=\"page42\" title=\"42\"/>",
"<span epub:type=\"pagebreak\" id=\"page43\" title=\"43\"/>",
"<span epub:type=\"pagebreak\" id=\"page44\" title=\"44\"/>",
"<span epub:type=\"pagebreak\" id=\"page45\" title=\"45\"/>",
"<span epub:type=\"pagebreak\" id=\"page46\" title=\"46\"/>",
"<span epub:type=\"pagebreak\" id=\"page47\" title=\"47\"/>",
"<span epub:type=\"pagebreak\" id=\"page48\" title=\"48\"/>",
"<span epub:type=\"pagebreak\" id=\"page49\" title=\"49\"/>",
"<span epub:type=\"pagebreak\" id=\"page50\" title=\"50\"/>",
"<span epub:type=\"pagebreak\" id=\"page51\" title=\"51\"/>",
"<span epub:type=\"pagebreak\" id=\"page52\" title=\"52\"/>",
"<span epub:type=\"pagebreak\" id=\"page53\" title=\"53\"/>",
"<span epub:type=\"pagebreak\" id=\"page54\" title=\"54\"/>",
"<span epub:type=\"pagebreak\" id=\"page55\" title=\"55\"/>",
"<span epub:type=\"pagebreak\" id=\"page56\" title=\"56\"/>",
"<span epub:type=\"pagebreak\" id=\"page57\" title=\"57\"/>",
"<span epub:type=\"pagebreak\" id=\"page60\" title=\"60\"/>",
"<span epub:type=\"pagebreak\" id=\"page61\" title=\"61\"/>",
"<span epub:type=\"pagebreak\" id=\"page62\" title=\"62\"/>",
"<span epub:type=\"pagebreak\" id=\"page63\" title=\"63\"/>",
"<span epub:type=\"pagebreak\" id=\"page64\" title=\"64\"/>",
"<span epub:type=\"pagebreak\" id=\"page65\" title=\"65\"/>",
"<span epub:type=\"pagebreak\" id=\"page66\" title=\"66\"/>",
"<span epub:type=\"pagebreak\" id=\"page67\" title=\"67\"/>",
"<span epub:type=\"pagebreak\" id=\"page68\" title=\"68\"/>",
"<span epub:type=\"pagebreak\" id=\"page69\" title=\"69\"/>",
"<span epub:type=\"pagebreak\" id=\"page70\" title=\"70\"/>",
"<span epub:type=\"pagebreak\" id=\"page71\" title=\"71\"/>",
"<span epub:type=\"pagebreak\" id=\"page72\" title=\"72\"/>",
"<span epub:type=\"pagebreak\" id=\"page73\" title=\"73\"/>",
"<span epub:type=\"pagebreak\" id=\"page74\" title=\"74\"/>",
"<span epub:type=\"pagebreak\" id=\"page75\" title=\"75\"/>",
"<span epub:type=\"pagebreak\" id=\"page76\" title=\"76\"/>",
"<span epub:type=\"pagebreak\" id=\"page77\" title=\"77\"/>",
"<span epub:type=\"pagebreak\" id=\"page78\" title=\"78\"/>",
"<span epub:type=\"pagebreak\" id=\"page79\" title=\"79\"/>",
"<span epub:type=\"pagebreak\" id=\"page80\" title=\"80\"/>",
"<span epub:type=\"pagebreak\" id=\"page81\" title=\"81\"/>",
"<span epub:type=\"pagebreak\" id=\"page82\" title=\"82\"/>",
"<span epub:type=\"pagebreak\" id=\"page83\" title=\"83\"/>",
"<span epub:type=\"pagebreak\" id=\"page84\" title=\"84\"/>",
"<span epub:type=\"pagebreak\" id=\"page85\" title=\"85\"/>",
"<span epub:type=\"pagebreak\" id=\"page86\" title=\"86\"/>"],

firstSentences: ["reformation he once desperately longed to see within it, largely",
"Catholic doctrinal innovations. In his 1837 Lectures on the Prophetical"
,"noteworthy of these was his sermon “The Theory of Developments",
"By his own admission, the study of the problem of development",
"and developing doctrine."
,"The new historical consciousness seized Newman, and",
"Only the faithful ones could hear of certain doctrines or participate",
"recognized that secret disciplines may explain the later emergence",
"Roman Catholic developments, which are “members of one family",
"otherwise, but here below to live is to change, and to be perfect is to",
"Wright, and Patrick Cochran have been invaluable aides throughout",
"through deqnition and description. Newman describes the qnal phase",
"Third, Newman challenges the possible objection that the text of",
"short of it, or that the sacred writer did not contemplate it, or that a",
"issues, Newman’s discussion of development remains one of the most",
"Presbyterian apologist James Orr (1844–1913) used evolutionary",
"Bible. In this sense, even this early evangelical approach to",
"Development was a considerable theme throughout Pelikan’s career,",
"According to Torrance, doctrinal formulation begins with the",
"to our analysis of doctrine.",
"postliberal, narrativist hermeneutic stems from engagement with the",
"encouragement and countless sacriqces helped me fulqll this calling.",
"According to this model,",
"theologically. In this use, theological interpretation has premodern",
"Development in The Nature of Doctrine",
"is only a serious “problem” for theologians committed to some kind",
"“rule theory” or cultural-linguistic approach, an approach shaped by",
"verbal regurgitation. Oftentimes new formulations of doctrines are",
"of the meaning a religion has for its adherents.”",
"inform those who are in covenant with God as his people how they",
"Most consequential for theoretical discussions of doctrinal",
"based on analogies drawn from biological evolution.",
"indebtedness to the similar enterprise of Thomas Torrance in the",
"with the working assumption that there is regularity in the natural",
"this means that members of the faith community learn to make use of",
"Though McGrath describes the process of development as “a",
"concern. Yet these theorists disagree about the precise nature of",
"biblical scholarship to contemporary hermeneutical theory. By all",
"Horizons] radically altered the way many evangelicals interpret the",
"Attempts to shelve Thiselton by locating him in a school of",
"the “craving for generality” found among philosophers, and by",
"appears to work with the conviction that truth, wherever found, can",
"exposition of particular doctrines and “often seem like an overture",
"exploration of what it means to be human. A descriptive theological",
"application all comprise a single, cohesive process.",
"academics deemed classical humanistic disciplines far less valuable",
"every good work” (2 Tim. 3:17). Doctrine is more than possessing",
"of the later New Testament documents and the subapostolic and early",
"The evidence for this “wedge” between qrst century faith",
"likely are rooted in one party or the other’s refusal to believe the word",
"may be atypical for the traditionalist and the progressive alike, but I",
"not choose their existence, nor do they choose their time and place",
"Consequently, many arguments against the propriety of doctrinal",
"logic, nor does he mean that the message of the Bible is relegated to",
"revealed or positive religion is that which contains the fewest",
"about Christ often ignore larger questions about the historical Jesus,",
"nature of propositional truth, what Thiselton calls a “weak” sense of",
"which John W. Cooper calls his “perichoretic panentheism,”",
"puzzlingly denies the notion of “temporal everlastingness” that is",
"of relevant passages.”",
"In his qfth and qnal charge against traditional conceptions of the",
"It is my recommendation to refrain using this term",
"itself remains intact” and the “hearer is summoned or called ‘under",
"development. In his Essay on development, John Henry Newman",
"and negative developments, Thiselton’s model of development is",
"development is Gadamer’s critique of objectivism in history and",
"recognize that historians operate in a particular historical context",
"on their judgment. On this point Gadamer is at least partially",
"the movement of the earth beneath our feet—but this change does",
"of concern that it leads to a hermeneutical relativism, or something",
"the author and his original audience. It is certainly not identical with",
"It seems that Gadamer himself would",
"With historic Christianity, evangelicals insist that all human persons",
"instrument of authority in the world today, but many of the moral",
"corrective to this Gadamerian tendency. Christian theology looks to",
"historical context of dialogue.",
"academy, Christian doctrine—how biblical texts are interpreted and",
"A hermeneutical dialectic of question and answer provides an",
"understanding, as Gadamer suggests, then it is reasonable to suspect a",
"lost in a new, third kind of nature, as Eutyches (c. 380–456) and the",
"consensus of the ecumenical councils. Like the period in which",
"debates over the so-called “New Perspective on Paul” are shaped"
,"Nonetheless, Thiselton’s model does raise a few additional",
"Scripture. Throughout this book, I hope to clarify some of these",
"posed by culture in Thiselton’s model, perceive traditional Christian",
"whether this particular theological framework qts under the “big",
"grounded in biblical exegesis and not merely derived from",
"Moltmann and Pannenberg] are distinctly excellent from a",
"or historical situation, nor is he interested in a theology that consists"
,"in biblical interpretation and Christian theology. However, in",
"describe his own theological program.",
"The Development of Vanhoozer’s",
"they “speak.” When the ink hits the page at Bible printing presses, no",
"presents between truth and method and attempts to reclaim method",
"the Bible that we must learn what has to be learned concerning the",
"critical and free of questions or categories that distort the meaning of",
"program. Vanhoozer, however, reframes the emphasis on",
"of doctrinal development because Vanhoozer suggests that general",
"reality. While the diperent strata apect each other in a vertical",
"Stratum Object Primary Method(s)",
"above) and preaching can and should aid in extracting and relaying",
"like the canonical-linguistic/theo-dramatic approach, are normative"
,"contemporary settings (sapientia).",
"very words that He chose, overrode their personalities.”",
"so much as to change in a way that would be faithful to, even though",
"these views with amalgamating dipering voices into a synthesized",
"Scripture. Bakhtin uses the term to describe the multiple unique",
"as is suggested in the fundamentalist theory of inspiration known",
"For Vanhoozer, chronotopes provide a means for discussing",
"epoch of its initial composition: “Trying to understand and explain",
"meaning of the text in the past or paying attention to the text’s",
"closedness and one-sidedness of these particular meanings, these"
,"horizon. This recognition prevents conrating the present situation",
"whose multivolume opus Theodramatik uses dramaturgical categories",
"and testimony in the composition of the four Gospels and in Acts) but",
"noting that while Balthasar focuses on the dramatic content of",
"dramatic model builds on the inruential work of Nicholas Lash,",
"The most important metaphor in the theo-dramatic approach for",
"action by disregarding the oper and attempting to take the narrative"
,"determining to confront the father who abandoned him as a child. A",
"So, what does this metaphor mean for doctrinal development? The",
"The most provocative metaphor Vanhoozer has employed to date",
"of Scripture. The locutionary acts of Scripture appear entirely",
"scholar Walter C. Kaiser Jr. contend that the dramatic metaphor is",
"He describes the process of development through Bakhtin’s notion",
"Church, preserved in the writings of the apostles and their qrst followers,",
"judgment in the life of the church. Vanhoozer’s model is not the qrst",
"But several practical questions remain. How does God exert his",
"Norms are, according to Tillich, “the criterion to which the",
"living ecclesial tradition embodied in councils and the papacy as",
"or revelation shapes the content of Christian belief, but because",
"However, not all evangelical biblicists understand the nature of",
"deqne the authority of the Bible in terms of its function or purpose.",
"considerable consequence for the reading of speciqc texts like",
"of the Bible and (2) the trustworthy character of God. Disagreement"
,"drew new lines of cultural identiqcation and loyalty, often resulting",
"personiqed by materialists) put the qnal nail in the proverbial cosn.",
"epistemic worth to cultural traditions and institutions including, but",
"The emphasis on reason isolated from authoritative tradition that",
"resemblances, epistemology and hermeneutics have diperent aims",
"The Inevitability and Necessity of Authoritative Tradition",
"which he examines and tests that knowledge.”",
"concedes that language “shapes the frame of reference through which",
"concepts, and with the concepts the meanings of words [and",
"disciples, the one nicknamed “the Twin,” was absent when these",
"of Scripture in interpretation. While the whole of Scripture should",
"Authorities such as Scripture and postcanonical"
,"communal utterances of belief passed from one generation to the next.",
"statements or testimonies provide grounds for doctrinal rerection",
"tradition as a valuable source for knowledge motivates the former",
"and suggested that “rationality”—even in science—is",
"Arguing for what he calls an “incommensurability of paradigms,”",
"thought grows out of the way in which the inner ordering of our",
"tradition or paradigm from which we work must change as well in",
"The most basic and most far-reaching issue for the authority problem",
"Hirsch separates the meaning of the text (“meaning-in”) given by an",
"and critics of evangelicalism who contend that historical",
"in each biblical text is single, deqnite and qxed.” Heeding Hirsch’s",
"search for a single, determinate meaning in every biblical text thus",
"While biblical interpretation and doctrinal development may allow",
"“worlds” are not mutually exclusive, as Tate and Thiselton rightly",
"Doctrinal development occurs in this world beyond the text.",
"these terms highlight “both the inruence of readers on texts and the",
"hermeneutical model of doctrinal development is the way in which",
"cannot have the qnal word. Revelation must serve a more sizable",
"community is central point of diperence between evangelical and",
"slightly modiqed arrangements. Thiselton concludes that the",
"2. The Bible alone communicates God’s will for humanity.",
"essential component of establishing continuity within the tradition.",
"describes interpretation as a performance wherein interpreters “make",
"meaning and belief of the community.",
"Lindbeck may want to asrm",
"earlier work in general hermeneutics, the guiding hermeneutical",
"to the act of revealing,",
"living sages for the present. However, performance of the script",
"to the abandonment of the theological task altogether. Making use",
"the text continues to transform the world in front of the text. The",
"deqnition, my asrmation of biblical inspiration and biblical",
"reality of space-time events, “our preaching and our faith are"
,"theologian George A. Lindbeck published The Nature of Doctrine",
"doctrines, as grammatical rules, are “second-order” statements that",
". . . as a truth claim with objective or ontological import, and thus",
"to both Lindbeck and his evangelical critics on the issue of religious",
"of religious experiences. Christian mystics like Meister Eckhart",
"philosophy. In this “turn,” many philosophers shifted their focus",
"Hungarian Army and later as a prisoner of war in Italian prison camps",
"value to a dog’s bark or cat’s meow or logical axioms to a Baroque",
"between uncritical or naïve biblicism and critical or nuanced biblicism."
,"religious language veriqcation, such as eschatological veriqcation",
"The Later Wittgenstein on the Many Uses of Language",
"language game, nor does their meaning remain the same between",
"meaning religious discourse takes in this non-cognitive view is in",
"Doctrinal language can serve many functions and depict reality",
"These scholars tend to create a false dichotomy between",
"has shown, can have multiple dimensions with diperent concurrent",
"Austin, Searle, and Religious Speech Acts",
"a) the speaker/writer is expressing a series of utterances with",
"writing with atheist philosopher James M. Smith, incorporated",
"a reality that has been long acknowledged in the Reformation",
"in the text, especially considering the materialist worldview of its",
"illocutionary acts, but neither did ancient pagan philosophers foresee",
"The primary purpose of speech-act theory is not epistemological;",
"assumption on my part (1) that mothers exist and (2) that mothers",
"act, but the illocutionary act or speaker’s intention can vary greatly",
"unnecessary dualistic tendencies in the interpretation of biblical texts,",
"would deny the propositional content of the creed (especially p2)",
"propositionalist understanding of the theological task, any bona qde"
,"the house. There may be more boxes to break open, but they are",
"Carl F. H. Henry, who is a frequent target of these kinds of criticisms",
"In Defense of Developing Doctrine",
"he believes that these often carelessly used terms create unnecessary",
"doctrine that recognizes ongoing participation, performance, and",
"between the various functions of speech acts and their dependence",
"Jesus as Lord, the speaker recognizes that Jesus, not Caesar or empire,",
"whether or not one asrms it—Jesus is his Lord, the one to whom he",
"propositional content. Mere assensus may describe the belief of",
"Scripture seeks to go beyond the “world of the text” to the “world",
"of doctrinal language to depict biblical and theological realities, but",
"Vanhoozer charges this practice, all too common in contemporary",
"No single Mitte or theological “center” abstracted from the Bible",
"development: in the transition from oral traditions to biblical texts, in",
"of Scripture. Doctrine must retain informative components because,",
"way is simply an extension of the path he forged between “absolute",
"diperent explanatory mechanisms and methodologies (determined",
"mental worlds that humans in their God-given creativity can produce",
"” or “preunderstanding,” the world of the reader before",
"may be metaphorical, but they are reality depicting in the sense that",
"perhaps because they were hoping, as many of us, for him to speak",
"enough in describing the tortuous, grueling realities of an",
"has numerous other metaphorical applications in ecclesiology,",
"contemporizing biblical judgments or concepts or ways of",
"not change but his followers are called to do so—to grow in their",
"So, how can hermeneutical theory address the tension between the",
"interpreter devoted to the supreme authority of Scripture recognizes",
"reality through a process of interpretive dialogue, dialogue that",
"doctrinal development as well: “Church tradition grows as a result of",
"theology that shows appreciation for alternative interpretations of",
"reading of Old Testament narratives.",
"believers that Paul addressed in his letters. “Coherence,” in contrast,",
"grasp of Paul’s coherent framework of thought, which can be",
"directed Christian action, Erasmus deems that the contingencies and",
"But McGrath also maintains that “Christian orthodoxy is as much",
"development of doctrine may raise signiqcant questions for many",
"Thiselton concludes, “The biblical writings are clearly not committed",
"Thiselton recognizes that coherence theories leave the possibility",
"the resurrection of Jesus makes possible a proleptic claim for the",
"come again to judge the quick and the dead. Furthermore, while",
"interpretation of Scripture are relevant for the present concern in",
"neopragmatic relativism or, in the case of the present discussion,"
,"recognizes that the interpretation of texts is open to revision. The task",
"speech acts, statements also function as self-involving commitments.",
"Bauer popularized this discontinuity thesis in their respective milieus,",
"hermeneutical theory and the problem of doctrinal development in",
"Newman were conceding changes in the tradition but making",
"ongoing task of developing doctrine and even opers valuable",
"understanding, or conviction upon which the believer draws to",
"who believes a proposition p ceases to believe p every time he or she",
"to say, “It is raining and she doesn’t believe it,” especially if “she”",
"if you like.’ It is a public act of self-commitment.”",
"Brown adds that the very notion of “heresy . . . presupposes",
"are inclined to doubt whether he does believe the proposition.”",
"certainty, ranging from disbelief or doubt to hesitant belief and on to",
"pneumatomachi (or “Spirit-qghters”), who argued that the Holy Spirit",
"In chapters 5–7, I identify three central problems or questions",
"series of interconnected, timeless propositions but rather as products",
"infers from the Cartesian tradition.",
"Self-involving belief stands not only in relation to the",
"as taking their stand and as staking their identity through sharing in",
"Our beliefs are like posts which we plant in the shifting sands of doubt",
"Doctrinal continuity is not primarily in cognitive",
"Vanhoozer is equally concerned about the modern description",
"Christian believers have the responsibility of taking up the mantle",
"identity (“one and the same” object or person) or in terms of",
"script. Sometimes in doctrinal development, non-biblical language",
"hermeneutics and the philosophy of language can assist in addressing"
,"The ipse/idem relationship prepares the reader for Vanhoozer’s third",
"Theological improvisation is also a never-ending task because the",
"With literary critic George Steiner, Vanhoozer renders translation",
"Rather than construing translation as reproduction, Vanhoozer",
"but in the same way a developing human fetus does not transform",
"Kelsey maintains that translation is incapable of",
"Vanhoozer’s second rejoinder to Kelsey is crucial for",
"emphasis on judgments rather than concepts also coheres with his",
"According to Vanhoozer, another mistake of the heretic is to mistake",
"Second, “each text predicates of these two subjects the most",
"theological problems associated with the facts of doctrinal",
"conceptuality of the day.”",
"fold minimize its historic signiqcance for all evangelicals, while others",
"Later on in the Reformation, Luther and Calvin likewise insisted that",
"Second, as Ben Witherington III and others have argued, many of",
"what we believe biblical authors dispositionally believed about the",
"Inerrancy may be a probable implication for those who asrm a",
"Thiselton briery addresses the debate between Joachim Jeremias",
"matter, attempts to show, how the practice of paedobaptism in their",
"sin (Rom. 6:11). In both cases, baptism appears to be a public act of",
"Concern about global overpopulation is not new to the twenty-",
"The question remains, what illocutionary act is he performing",
"understanding—looking at the canon as a whole as the script for",
"reign (Gen. 1:28b). The earth serves humanity, not humanity the",
"The real “problem” in doctrinal development is the issue of doctrinal",
"Vanhoozer’s use of ipse/idem does raise other concerns. One might",
"and uniqed leadership, particular expressions of the church in every",
"continuity is not in expressions or even shared conceptual",
"Prima facie, the need for theories of development in Roman",
"“the True Vine,” and many others. But no one of these titles or",
"The Value of Hermeneutical Models",
"practice of hermeneutics is reciprocally historical in nature, as",
"acknowledge its otherness can result in the vision of an overly",
"these challenges are far to complex to leave entirely in the hands",
"hermeneutics provides a way to describe the nature of theological",
"those judgments in new settings, even utilizing new or diperent",
"academy or the sale of books—takes precedence in the task of",
"authority is more than a cognitive asrmation of the Bible’s",
"inferences from ancient settings about what God might have us do",
"Unlike a hermeneutics of suspicion that would distrust the motives",
"“portable narratives.” Doctrines are like the biblical story packed in a",
"and theological realities competently and honestly. Second, trust in",
"Biblical texts with closed meanings do not change under the",
"human authorship asrms, but its interpreters are prone to error.",
"correct our previously held assumptions. We need to be teachable",
"mirror dimly but then face to face. Now [we] know [read, interpret]",
"speech informed by historical and theological traditions, written for",
"discourse may vary from context to context, but the guiding norm of",
"world because biblical authors would not have thought in such terms.",
"features between traditions is astonishing. Anglican, Baptist,"
,"disculties certain biblical texts pose. Even among evangelicals where",
"doctrines or teachings. One such discipline, biblical theology—the",
"the same biblical texts. This does not mean that the meaning of",
"Catholic theologians anticipated many of the issues in the abortion",
"This book has addressed two key issues theological prolegomena",
"Every successive generation of Christian believers has a",
"———. New Horizons in Hermeneutics: The Theory and Practice of Transforming",
"and Theological Hermeneutics.” In The Promise of Hermeneutics, ed.",
"———. “The Parables as Language-Event: Some Comments on Fuch’s",
"———. “Word (Logos): Language and Meaning in Religion.” In The New",
"Everyday Theology: How to Read Cultural Texts and Interpret Trends. Grand",
"a continuing tradition characterised by a deep intertwining of faith",
"———. “Disputing about Words? Of Fallible Foundations and Modest",
"———. “From Speech Acts to Scripture Acts: The Covenant of Discourse",
"———. “May We Go Beyond What Is Written After All? The Pattern",
"———. “Ricoeur, Paul.” In Dictionary for Theological Interpretation of the Bible,",
"———. “Word of God.” In Dictionary for Theological Interpretation of the Bible,",
"Wittgenstein’s Impact on Theology.” Journal of the Evangelical Theological",
"Barkun, Michael. Religion and the Racist Right: The Origins of the Christian",
"Bauckham, Richard. Jesus and the God of Israel: God Cruciaed and Other",
"Blackburn, Simon. The Oxford Dictionary of Philosophy. Oxford: Oxford",
"Bright, Michael H. “English Literary Romanticism and the Oxford"
,"a created being who has “God-like” qualities. For the Nicene fathers,",
"Butler, Joseph. Analogy of Religion: Natural and Revealed to the Constitution",
"———. The Mind of the Oxford Movement. Stanford: Stanford University Press,",
"Cooper, John W. Panentheism: The Other God of the Philosophers. Grand",
"Descartes, René. Discourse on the Method for Rightly Conducting One’s Reason",
"———. “Toward the Revision of the Present State of Theology.” In Romance",
"———. The Orthodox Corruption of Scripture: The E`ect of Early Christological",
"———. The Story of Christ in the Ethics of Paul: An Analysis of the Function",
"Gilkey, Landon. “Cosmology, Ontology, and the Travail of Biblical",
"Papers from the Ninth International Conference on Patristic Studies, September",
"———. Vincent of Lérins and the Development of Christian Doctrine. Grand",
"But to put things in perspective, these creeds, written approximately",
"Hasel, Gerhard. New Testament Theology: Basic Issues in the Current Debate.",
"Hitchens, Christopher. God is Not Great: How Religion Poisons Everything.",
"Hurtado, Larry W. How on Earth Did Jesus Become a God? Historical Questions",
"———. The Origins of Infant Baptism: A Further Study in Reply to Kurt Aland.",
"Keener, Craig. The Historical Jesus of the Gospels. Grand Rapids, MI:",
"Lash, Nicholas. Change in Focus: A Study of Doctrinal Change and Continuity.",
"———. “The Bible as Realistic Narrative.” Journal of Ecumenical Studies 17",
"Lotman, Jurij. The Structure of the Artistic Text. Ann Arbor: University of",
"Malina, Bruce J. The New Testament World: Insights from Cultural",
"———. Metaphorical Theology: Models of God in Religious Language.",
"any open-minded reader from any cultural or historical context can",
"McGrath, Mark G. The Vatican Council’s Teaching on the Evolution of Dogma.",
"———. “What is Truth? Truth and Contemporary Culture.” Journal of the",
"Murphy, Nancey C. Beyond Liberalism and Fundamentalism: How Modern",
"Hermeneutics.” In Biblical Hermeneutics: A Comprehensive Introduction to",
"of ‘Descriptive Biblical Theology.’” Horizons in Biblical Theology 8 (1986):",
"———. Theology and the Philosophy of Science. Translated by Francis",
"———. Obedient Rebels: Catholic Substance and Protestant Principle in Luther’s",
"Polkinghorne, John. One World: The Interaction of Science and Theology.",
"———. “Philosophical Roots of Phenomenological and Structuralist Literary",
"———. Freud and Philosophy: An Essay on Interpretation. Translated by Denis",
"a figure of speech drawn from Greek athletic contests, Jude pled",
"Rogers, Jack B., and Donald K. McKim. The Authority and Interpretation of the",
"of the Relation of Herder’s Literary Idiom To His World-View. The Hague:",
"Consciousness.” In Recent Themes in Historical Thinking: Historians in",
"Stenger, Victor J. God: The Failed Hypothesis—How Science Shows That God",
"———. How Modern Should Theology Be? Translated by H. George Anderson.",
"———. Reality and Evangelical Theology: The Realism of Christian Revelation.",
"renaissance catholique en Angleterre.” Revue des sciences philosophiques et",
"Walgrave, Jan Henrik. Unfolding Revelation: The Nature of Doctrinal",
"———. Slaves, Women &amp; Homosexuals: Exploring the Hermeneutics of Cultural",
"Winch, Peter. The Idea of a Social Science and Its Relationship to Philosophy.",
"Development may also describe (2) attempts to contextualize or",
"Wolterstorp, Nicholas. Divine Discourse: Philosophical Rebections on the Claim",
"to the Recovery of Theological Exegesis.” In Theological Interpretation of",
"cognitivity of religious language,"
,"148-65; as hermeneutical",
"Fundamentalism and Evangelicals,",
"Other developments or shifts appear within the early Christian",
"theological interpretation of"
,"Christian history is a witness to the ongoing development of",
"as an authoritative list of books was an even later development, and",
"Greco-Roman philosophy to defend the Christian tradition from",
"systematic theologian address current crises and still maintain",
"distinctive Catholic doctrines like the doctrines of papal infallibility,",
"Protestants and evangelicals who contend that there is an ongoing",
"development is valuable in distinguishing between atting and unatting",
"committed to some form of biblicism face signiqcant theological",
"range over functions, properties, relations, and classes of objects,",
"also calls on the insights of literary criticism and the philosophy of",
"While it bears certain similarities to epistemology (i.e., the",
"(1912–2001) once described church history as the “history of the",
"my fellow evangelical readers who eschew all things philosophical",
"still, in the language of the Christian tradition, are a priori refusals to",
"contemporary hermeneutical theory, evangelicals should cautiously",
"only is it through Jesus Christ alone that we know God, but it is only",
"mere historical evaluation of biblical texts and to think about the",
"and role of biblical discourse in theology and interpret the Bible",
"identify as a progenitor of their movement, they understand the",
"they often seem to be from diperent planets. They often speak in",
"theology and biblical studies qrst forged by Johann Philipp Gabler",
"knowledge of God in Christ, there is no true knowledge of the",
"A detailed historical account of either hermeneutics or the problem",
"since the Second Vatican Council. Roman Catholic theologians have",
"understanding of the Christian faith and assumed that doctrinal",
"church alike should progress in their understandings of doctrine:",
"Vincent maintains that the biblical canon is “complete” and",
"development in the nineteenth century."
,"and his own views on the nature of the church. Luther here rails",
"Eutyches (c. 380–456) was their rejection of the doctrine of the",
"Some Catholic Reformers (or Counter-Reformers) made very",
"doctrinal corruption. The bishop describes the relationship between",
"Hermeneutics and Development",
"hermeneutics—moving “the art of understanding” out of the realm",
"and eighteenth centuries had profound epects on the natural sciences,",
"the world, came into its own in modern times, which had become",
"The recognition of religious plurality by philosophers of religion",
"attempted to forge a new way",
"of the practice of sacramental confession sparked Drey’s interest in",
"nature of reality, which is beyond mechanical dissection. During this",
"Drey desired to produce a defense of Christian theology that could",
"Drey formulated a theory of doctrinal development that contrasted",
"If Scripture alone is accepted as the means of the tradition of ideas",
"Christianity’s internal history is its essence, its living history.",
"Nevertheless, Drey warns that not every doctrinal development of",
"errors and schisms; it is responsible for the maintenance of religious",
"interpretation. Grammatical interpretation addresses the nature of",
"understandings of theology, religious consciousness, and",
"Newman, unlike the Tübingen Catholics, is not concerned with"]
}

